name: Bug Report
description: This is for bugs and general problems.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! It helps to make sure Cockpit works well everyone, including you!
  - type: textarea
    id: what-happened
    attributes:
      label: Explain what happens
      description: |
        Include steps on how to reproduce. Including screenshots is very helpful.
      value: |
        1. 
        2. 
        3. 


    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### :information_source: Please note
        
        - If you want to discuss something, [post a new discussion](https://github.com/cockpit-project/cockpit/discussions/new) in our [discussion forum](https://github.com/cockpit-project/cockpit/discussions).
        - If you have a problem with a component, those issues are filed elsewhere: [Machines](https://github.com/cockpit-project/cockpit-machines/issues/new), [Podman](https://github.com/cockpit-project/cockpit-podman/issues/new/choose), [OStree](https://github.com/cockpit-project/cockpit-ostree/issues/new), or the [starter kit](https://github.com/cockpit-project/starter-kit/issues/new). 

        ---

        _Everything below is optional, but useful for us to help fix the problem._
  - type: dropdown
    id: os-server
    attributes:
      label: Server operating system
      description: Which Linux distribution are you using on the server where Cockpit is installed?
      options:
        - Arch Linux
        - CentOS
        - CentOS Stream
        - Clear Linux
        - Debian
        - Fedora CoreOS
        - Fedora Linux
        - Red Hat Enterprise Linux
        - Ubuntu
        - openSUSE Leap
        - openSUSE Tumbleweed
        - other
    validations:
      required: false
  - type: input
    id: os-version
    attributes:
      label: Server operating system version
      description: Which version of the above selected operating system are you using? (This is especially useful, if it's not the latest version.)
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using?
      description: |
        Including browser information helps with debugging, especially if things look odd or if pages are blank.
      multiple: true
      options:
        - Firefox
        - Chrome
        - Edge
        - Brave
        - Safari
        - GNOME Web
        - Cockpit Client / Cockpit Desktop
        - Other (specify in the comments)
  - type: input
    id: os-client
    attributes:
      label: Client operating system
      description: |
        Please share the operating system where you're using the browser.
      placeholder: |
        examples: Windows 10, macOS 12.2, iOS 15.3, Fedora 35, etc.
    validations:
      required: false
  - type: dropdown
    id: page
    attributes:
      label: Page
      description: |
        Which part of Cockpit is affected?
      options:
        - not applicable / unspecified
        - overview
        - metrics
        - logs
        - storage
        - networking
        - user accounts
        - services
        - software updates
        - terminal
        - selinux
        - shell
  - type: textarea
    id: logs
    attributes:
      label: System log
      description: |
        Relevant parts of the server's log are useful.  This will be automatically formatted, backticks are not needed.

        - If the issue happened in the last 10 minutes, use: `journalctl --since -10m`
        - If you know which systemd unit was affected, use: `journalctl -u cockpit -u <unit>`

        Leave empty if unsure or if this doesn't apply.
      render: shell
